# Generated by Django 4.2.7 on 2026-09-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
